### ISSUE TITLE
Xml PI can not be in the first line

### ISSUE THREAD

**Issue by cozdiker-sps** [kobjects/ktxml#5]
https://github.com/kobjects/ktxml/blob/2ff18fee499c1ead0a0e9c70737a43e95f684872/core/src/commonMain/kotlin/org/kobjects/ktxml/mini/MiniXmlPullParser.kt#L248

In this line basically it doesn't let me to parse an XML file which starts with "<?XML"

Why a PI starting with "XML" should be in the lineNumber "1"? Because when i parse a file the line number equals "0"

**Comment by msasikanth** [comment]
Hi, I used to get this error previously and ended up just removing the "<?XML" declaration from the content. But after the update most of the sources worked fine without having to remove it.

But there are still some sources that throw errors, I tried debugging it but I am unsure what the cause for it is. Any idea? 🤔 

www.terminologiaetc.it/feed

**Comment by msasikanth** [comment]
Getting the following error

```
org.kobjects.ktxml.api.XmlPullParserException: PI must not start with xml
                 Position: PROCESSING_INSTRUCTION ﻿@1:5
                 	at org.kobjects.ktxml.mini.MiniXmlPullParser.exception(MiniXmlPullParser.kt:175)
                 	at org.kobjects.ktxml.mini.MiniXmlPullParser.error(MiniXmlPullParser.kt:170)
                 	at org.kobjects.ktxml.mini.MiniXmlPullParser.parseLegacy(MiniXmlPullParser.kt:254)
                 	at org.kobjects.ktxml.mini.MiniXmlPullParser.nextImpl(MiniXmlPullParser.kt:228)
                 	at org.kobjects.ktxml.mini.MiniXmlPullParser.next(MiniXmlPullParser.kt:777)
                 	at org.kobjects.ktxml.api.XmlPullParser$DefaultImpls.nextTag(XmlPullParser.kt:553)
                 	at org.kobjects.ktxml.mini.MiniXmlPullParser.nextTag(MiniXmlPullParser.kt:12)
                 	at dev.sasikanth.rss.reader.core.network.parser.FeedParser$parse$2.invokeSuspend(FeedParser.kt:46)
                 	at dev.sasikanth.rss.reader.core.network.parser.FeedParser$parse$2.invoke(Unknown Source:8)
                 	at dev.sasikanth.rss.reader.core.network.parser.FeedParser$parse$2.invoke(Unknown Source:4)
                 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:43)
                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
                 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                 	at dev.sasikanth.rss.reader.core.network.parser.FeedParser.parse(FeedParser.kt:43)
                 	at dev.sasikanth.rss.reader.core.network.fetcher.FeedFetcher.parseContent(FeedFetcher.kt:98)
                 	at dev.sasikanth.rss.reader.core.network.fetcher.FeedFetcher.fetch(FeedFetcher.kt:69)
                 	at dev.sasikanth.rss.reader.core.network.fetcher.FeedFetcher.access$fetch(FeedFetcher.kt:41)
                 	at dev.sasikanth.rss.reader.core.network.fetcher.FeedFetcher$fetch$2.invokeSuspend(Unknown Source:16)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
                 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
```

**Comment by msasikanth** [comment]
fwiw, if I enable relaxed mode this particular feed is parsed correctly.

**Comment by stefanhaustein** [comment]
I have added a test case for (the current state of) this feed and it seems to work fine....?

(and as it seems to be utf8 there shouldn't be any funny things like bom characters(?))

P.S.: If you see this again, can you attach a hex dump of the first bytes coming in from the stream?

**Comment by stefanhaustein** [comment]
PPS: It looks like this is some kind of BOM after all:

```
haustein@Stefans-Mini ~ % curl https://www.terminologiaetc.it/feed/ > dump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20151    0 20151    0     0  92344      0 --:--:-- --:--:-- --:--:-- 92435
haustein@Stefans-Mini ~ % hexdump dump
0000000 bbef 3cbf 783f 6c6d 7620 7265 6973 6e6f
```

**Comment by stefanhaustein** [comment]
So I think this particular stream includes some form of invalid byte order mark (valid BOMs are listed here: https://en.wikipedia.org/wiki/Byte_order_mark#Byte-order_marks_by_encoding ). 

So even if I would extend the parser to accept a valid BOM (which I think should be handled at the unicode decoder level), this particular stream would probably not parse in strict mode...

**Comment by msasikanth** [comment]
Thanks for checking it out. I guess I will stick with relaxed mode for now, it also handles other content parsing exceptions if they have not well formatted HTML content. We can close this issue again 🙏🏾
